name: Golang Docker Build

on:
  push:
    branches:
      - "**" # Trigger on push to all branches
  release:
    types: [published]

env:
  CONTAINER_REPOSITORY: quay.io/michielmurphy # Change to your actual Quay.io username
  CONTAINER_IMAGE: alm-workshop
  GOLANG_VERSION: 1.23

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Quay.io Robot Account
      - name: Login to Quay.io with Robot Account
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_ROBOT_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: quay.io/michielmurphy/alm-workshop

        # Set the version tag when a GitHub release is created
      - name: Set Docker Image Tag
        id: set_tag
        run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
            echo "IMAGE_TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=latest" >> $GITHUB_ENV
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
#docker command: docker run -p 3000:3000 quay.io/michielmurphy/alm-workshop:main
